[package]
name = "ethereum_serde_utils"
version = "0.8.1"
edition = "2021"
description = "Serialization and deserialization utilities for JSON representations of Ethereum types"
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/sigp/ethereum_serde_utils"
documentation = "https://docs.rs/ethereum_serde_utils"
keywords = ["ethereum"]
categories = ["cryptography::cryptocurrencies"]

[lib]
name = "serde_utils"

[dependencies]
alloy-primitives = { version = "1.0", default-features = false, features = ["serde"] }
serde = { version = "1.0.0", default-features = false, features = ["derive", "alloc"] }
serde_derive = "1.0.0"
serde_json = { version = "1.0.0", default-features = false, features = ["alloc"] }
hex = { version = "0.4.3", default-features = false, features = ["alloc"] }

[features]
default = ["std"]
std = ["alloy-primitives/std", "serde/std", "serde_json/std", "hex/std"]
